# Generated by Django 4.0.5 on 2022-06-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='id_servicio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
